/** @type {import('@get docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // API Guide takes the top slot
    {
      type: 'doc',
      id: 'index', 
      label: '📊 API Overview & Guides',
    },
    // interactive Swagger endpoint sandbox parameters match this folder block
    {
      type: 'category',
      label: '🔌 Interactive API Sandbox',
      link: {
        type: 'generated-index',
        title: 'DataHub API Playground',
        description: 'Live interactive sandbox queries generated straight from OpenAPI specs.',
        slug: '/api',
      },
      // Points directly to the subfolder directory generated by terminal command
      items: require('./docs/api/sidebar.js'),
    },
  ],
};

module.exports = sidebars;
