name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main # Triggers every time you push edits to main

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Project Dependencies
        run: npm ci

      - name: Compile API Schemas
        run: npx docusaurus gen-api-docs all

      - name: Build and Publish Website
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: gh-pages # Deploys the static site to the gh-pages workspace
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
